Cargo.lock, server/src/http.rs, service/src/backend/local_fs.rs, service/src/backend/mod.rs, service/src/backend/s3_compatible.rs, service/src/lib.rs, stresstest/Cargo.toml, stresstest/example.yaml, stresstest/src/config.rs, stresstest/src/http.rs, stresstest/src/main.rs, stresstest/src/stresstest.rs, stresstest/src/workload.rs
The stresstester now cleans up after itself, running a `delete` on all the left-over files.
It is also configurable via a yaml format now.
=> Implement cleanup and configurability in `stresstest`

.github/workflows/ci.yml, .github/workflows/image.yml
Fixes the branch trigger for CI on `main`, adds CI for `release` branches once we start publishing, and disables docker image builds in PRs to speed up CI and save resources while they are not needed.
=> ci(gha): Fix CI triggers and job names

Dockerfile.stresstest
Similar to https://github.com/getsentry/foundational-storage/pull/35, but builds
the stresstest in a separate dockerfile.
=> build(docker): Separate dockerfile for stresstest build

README.md
This repository is specifically for the object storage platform. This updates
the readme, adds a bit more information on the architecture, and separates
utilities from development.
=> meta: Update objectstore readme

stresstest/example.yaml, stresstest/src/http.rs, stresstest/src/stresstest.rs, stresstest/src/workload.rs
Instead of using the opaque "allocate me some ids" request, it will now use its own random ids as keys, so that makes it work with any s3-compatible storage directly.
=> Make stresstest allocate its own keys

.github/workflows/ci.yml
Uses the same approach as Relay to render cargo docs and deploy them to GitHub
pages so that they can be accessed via getsentry.github.io/objectstore. This
allows us to publish code-level architecture documentation and usage docs for
the Rust client.
=> ci: Render and deploy cargo docs to GH pages

Cargo.lock, objectstore-server/Cargo.toml, objectstore-server/tests/stresstest.rs, stresstest/src/http.rs, stresstest/src/lib.rs, stresstest/src/main.rs, stresstest/src/stresstest.rs, stresstest/src/workload.rs
Adds an integration test to the `objectstore-server` crate that spawns the full
server in a subprocess and then runs the stresstest against it for 10 seconds.
To do so, the `stresstest` crate has been split into a library and binary:
- Workload definition and the stresstest itself are in the library and can be
called via `stresstest::run`.
- YAML configuration and a main function that reads config, configures
workloads, and then runs the stresstest remain in the binary.
The initial stresstest integration test is not meant to mimic any real workload
and it does not run in release mode. Rather, it is used to integration-test the
stresstest with the binary. In a follow-up, I want to use `objectstore-sdk` in
stresstest, to ensure the client can talk to the server.
=> test: Add an integration test using stresstest as a library

Cargo.lock, objectstore-server/Cargo.toml, objectstore-server/src/http.rs
0.3.2 introduces the `wait_owned()` wait variant which makes axum's `with_graceful_shutdown` a bit nicer.
Also a drive-by change, adding `.shutdown_on_drop()` to the guard, as presumably the service should stop if axum fails/panics.
=> ref(deps): Update elegant-departure to 0.3.2

stresstest/example.yaml, stresstest/src/config.rs, stresstest/src/main.rs, stresstest/src/stresstest.rs, stresstest/src/workload.rs
Adds a second opt-in mode for stresstests to define constant throughput rather
than constant concurrency. This allows us to test the traffic patterns of our
use case across iterations of the server with different latency. Also, it allows
us to more effectively assess the latency of the service at specific throughput.
=> feat(stresstest): Implement throughput mode

.envrc, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, Dockerfile, README.md, devservices/config.yml, objectstore-server/src/config.rs, objectstore-server/src/state.rs, objectstore-service/Cargo.toml, objectstore-service/src/backend/bigtable.rs, objectstore-service/src/backend/mod.rs, objectstore-service/src/lib.rs, objectstore-types/src/lib.rs
First iteration of a Google BigTable backend that supports
- Concurrent uploads and downloads
- Table management: Automatically creates the table, column families, and GC policies.
- Overwriting objects: When calling `put` on an object that exists, the old one will be deleted along with its metadata.
- TTL and TTI: Automatic expiry of objects after a time-to-live, as well as automatic bumping via time-to-idle. The latter has to be implemented as re-inserting, so the bump is debounced to once per day.
- Metadata storage: Encodes the metadata map, including custom metadata, into a dedicated column.
Locally and in CI this is tested using the BigTable Emulator. The emulator is also added to devservices for convenience. Unfortunately, we had to bring back `protoc` since this is required by one …
=> feat: Implement a simple backend for Google BigTable

Cargo.toml
This seems to have been removed unintentionally as a drive-by refactor. Brings
back our usual profile management that we also use in Relay and Symbolicator. 
By default, debug information is disabled in development to speed up the build
and reduce the target folder size. In a `dev-debug` profile or in `release`,
debug information is enabled.
=> build: Disable debug in dev again

.github/workflows/build.yml, Dockerfile
Switches to a much smaller and more lightweight distroless Docker base image. The amd64 and arm64 are built directly on the GHA runners and copied into the Docker image.
=> ci(gha): Build release binary natively and switch to distroless image

.github/workflows/build.yml, Dockerfile
The runner image was too new for objectstore to run on debian-12. This downgrades the runner and adds a smoketest to verify that the binary can run in the container.
=> fix(build): Downgrade build runner and use nonroot image

.envrc, objectstore-server/src/main.rs
We still support `RUST_LOG`, but objectstore now applies better defaults on its
own dependencies to reduce noise in logging.
By default, objectstore uses INFO as log level. In our own development
environment we override this to DEBUG, so we have more visibility by default.
TRACE would be possible, too, but is quite verbose for a usual test run.
If the user configures complex `RUST_LOG` directives, we will still honor them
and apply them directly as env filter to the tracing library. If `RUST_LOG` is
set to a simple level, however, we apply custom logic:
- Our own crates and `tower_http` will go up to TRACE, but no higher than the
configured log level from `RUST_LOG`.
- `trust_dns_proto` is known to be very spammy on INFO, so we mute it to `WARN`.
- Everything else logs on `INFO`.
The …
=> ref(server): Improve logging

Cargo.lock, objectstore-server/Cargo.toml, objectstore-server/src/main.rs
To support rustls on distroless, we have to install a crypto provider
explicitly. This is required for gcp_auth.
=> fix: Support rustls on distroless

Cargo.lock, objectstore-server/Cargo.toml, objectstore-server/src/http.rs, objectstore-server/src/main.rs
Refactors the server startup code, inspired by Relay's startup routines. This
separates routes from middlewares, binds an explicit listener so we can control
the listen backlog, and adds middlewares to track request errors and panics.
Refs FS-114
=> ref(server): Modularize startup code and add middlewares

stresstest/example.yaml, stresstest/src/config.rs, stresstest/src/http.rs, stresstest/src/main.rs, stresstest/src/stresstest.rs, stresstest/src/workload.rs
Makes the stresstest more realistic by writing multiple usecases and scopes.
The name of each concurrent workload is used as usecase, which also mimics
production behavior more closely. Also, each workload can specify a number of
organizations (defaulting to 1), which is used as scope.
Internally, we create a project-level scope, since this is what the real
usecases will also be doing. We reuse the org ID as project ID.
=> ref(stresstest): Distribute workloads across usecases and orgs

Cargo.lock, Cargo.toml
This bumps `merni` for a critical fix that will now properly submit large metrics packets, as well as running `cargo update` for good measure.
=> chore: Update `merni` and other dependencies

objectstore-service/src/backend/bigtable.rs, objectstore-service/src/backend/gcs.rs, objectstore-service/src/backend/local_fs.rs, objectstore-service/src/backend/mod.rs, objectstore-service/src/backend/s3_compatible.rs, objectstore-service/src/lib.rs, objectstore-service/src/path.rs
This introduces a `name` to the generic backends, which we emit as a separate metrics tag now.
=> ref: Give backends a name

Cargo.lock, objectstore-server/Cargo.toml, objectstore-server/src/config.rs, objectstore-server/src/observability.rs
adds a `Secret` newtype around `String` which:
- does not implement `Display`
- writes `"[redacted]"` in its `Debug` implementation
- allows access to the underlying secret as a `&str` via `secret.access()`
we already do `debug!(?config)` and inevitably we will add things like `debug!(?request.headers); // Temporary log to debug #1234`. use this type when you have the opportunity for values you recognize are sensitive so that logging like this doesn't cause an incident
the sentry dsn and datadog key are not "defcon 0" secrets but they are definitely non-public and we will probably have more sensitive examples in the future
=> fix: Add Secret newtype to avoid config secrets in logs

objectstore-client/src/client.rs, objectstore-client/src/get.rs, objectstore-client/src/put.rs, objectstore-client/src/tests.rs, objectstore-server/src/http.rs
ref FS-154
this only adds the most basic healthcheck, as we don’t have a concept of "readiness" yet.
=> feat: Add a healthcheck endpoint, moving existing routes to `v1/`

.envrc, Cargo.lock, objectstore-server/src/http.rs, objectstore-server/src/main.rs, objectstore-server/src/observability.rs, objectstore-service/Cargo.toml, objectstore-service/src/backend/bigtable.rs, objectstore-service/src/backend/gcs.rs, objectstore-service/src/backend/local_fs.rs, objectstore-service/src/backend/s3_compatible.rs
- sets our spans to `info` level so they will be sent to sentry
- cleans up our `EnvFilter` usage. we don't use the dns crate that was referenced before, we had the wrong name for one of our targets, and with our spans set to `info` we can disable the noise from `tower_http`.
- if we want to re-add the capability to put a level filter specifically on printing, IMO that should be a separate env var. i think it is weird that `RUST_LOG=debug` means `RUST_LOG=debug` for the console and `RUST_LOG=INFO,objectstore=TRACE...` for spans.
- adds a few spans and a bunch of `debug!()`s to see a very basic "story" when uploads pass through
the "logs" tab in sentry does not get any of the span context surrounding the log so it is not very useful. i will look into whether anything special has to be done …
=> chore: add basic debug logs and adjust span log levels

.github/workflows/build.yml, .github/workflows/ci.yml
enabling merge queues before doing this means it will wait forever for required workflows that are never triggered
=> ci: enable ci workflows to run on merge_group trigger

objectstore-service/src/backend/bigtable.rs, objectstore-service/src/backend/gcs.rs, objectstore-service/src/backend/local_fs.rs, objectstore-service/src/backend/s3_compatible.rs, objectstore-service/src/lib.rs, objectstore-types/src/lib.rs
only implements these metrics in GCS/Bigtable, not local_fs or s3_compatible.
regarding the size metric in GET requests: GCS will calculate the size for us and populate it in the metadata response. Bigtable doesn't, but we load entire Bigtable objects into memory so we compute the size and set it in the GET handler. alternatively, we could write the size into the metadata at PUT time so it will be deserialized automatically at GET time, but the trait interface takes `&Metadata` and that would have to change.
regarding deletes: if we need to speed those up, we should either make the second backend attempt contingent on a `NOT_FOUND` from the first attempt or run both attempts concurrently. currently you must run both in sequence.
also, i notice the retry logic in the bigtable impl does not …
=> feat: latency metric for GET/DELETE, size metric for GET requests

.github/workflows/build.yml, .github/workflows/ci.yml
Since we enabled merge queues, every merged PR was built & pushed twice. Since the merge group commits land directly in the main branch, we can skip building there. 
This assumes that we will not have workflows bypassing the merge queue. If we add such workflows in the future, we can revise.
=> build: Exclusively build on merge_group and not main branch

Cargo.lock, devservices/config.yml, objectstore-server/Cargo.toml, objectstore-server/src/config.rs, objectstore-server/src/http.rs, objectstore-server/src/observability.rs, objectstore-server/tests/stresstest.rs, objectstore-service/src/backend/bigtable.rs, objectstore-service/src/backend/gcs.rs, objectstore-service/src/backend/local_fs.rs, objectstore-service/src/backend/s3_compatible.rs
Introduces configurable log formats very similar to how Relay handles it. The
default is "auto", which infers the right format from the TTY. On attended
sessions, the default format is "pretty" with colors, otherwise a plain text
version. For production, there's a JSON format option.
Also switches back all tracing instruments to `trace` level, as they are way too
verbose for either INFO or DEBUG level. Especially on INFO, we would cause
significant cost on cloud logs.
=> fix(observability): Introduce configurable log formats
